name: metapdf
description: MetaPDF — Yapay Zekâ Destekli Dijital Kitap Okuyucu
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.5.2
  file_picker: ^5.2.5
  pdf_text: ^1.0.0
  http: ^0.13.6
  audioplayers: ^2.1.1

flutter:
  uses-material-design: true
